### ISSUE TITLE
Installation of Maximo Application Suite on Mac

### ISSUE THREAD

**Issue by DavidMecalco** [evilADevil/mas-local#10]
When the script is executed, it shows the following error:

1.	./masinst.sh: line 103: syntax error near unexpected token `('
2.	./masinst.sh: line 103: `This is no more needed from CRC 2.11.0, because there is an equivalent default storage class (crc-csi-hostpath-provisioner)'

![image](https://github.com/evilADevil/mas-local/assets/66454464/0b36089d-0c86-4d80-a38d-037be326ed56)

Reviewing the error, the specific line of code is as follows:

![image](https://github.com/evilADevil/mas-local/assets/66454464/c29c38e8-3114-4282-a71b-5519fc27b33e)

Commenting out line 103, the script continues to work without any issues.

![image](https://github.com/evilADevil/mas-local/assets/66454464/3bc2368e-79fe-464f-9453-742364ab26d6)

We checked the OpenShift console and the pod specified in the terminal to view the logs and monitor the installation progress.

![image](https://github.com/evilADevil/mas-local/assets/66454464/e5a944c5-03a0-440b-b2e5-fef5bb80b946)

The issue lies in the fact that the BM Cloud Pak foundational services operator cannot be installed, and the pod ibm-common-service-operator cannot be deployed.

For the operator, we have the following error message:

![image](https://github.com/evilADevil/mas-local/assets/66454464/fdc07bea-a21e-4f37-b9ae-217cb0e7589e)

For the pod, we have the following error message: 

![image](https://github.com/evilADevil/mas-local/assets/66454464/1258f228-ffa1-4cd2-a482-ec756c844755)

Those have been the issues we encountered while attempting to install Maximo Application Suite using this method.

**Comment by liyongc** [comment]
@DavidMecalco, looks very weird here that the cloud-pak foundation service could not installed on the CRC cluster with the above error "0/1 node available", can you check the node status by issuing below command line 
1. `oc get node` to see if the worker is running well 
2. `oc get pods -A | grep -i Evi 'complete|1/1|2/2|3/3|4/4|5/5|6/6'` to see if there are pods in unhealthy status

And if there's no error popup, can you help to open the CRC dashboard and manually remove/re-install the IBM foundational service to see if it works or not?

I will try to re-produce the issue in my local MAC system if I have a chance and see if it could help to solve it as well.

**Comment by DavidMecalco** [comment]
@liyongc Hello, I have completed the corresponding steps to inspect what has happened within the cluster, it seems that everything is working fine.

![imagen](https://github.com/evilADevil/mas-local/assets/66454464/c1615b42-ed32-481f-8669-ba4a6f2ad706)

I have also repeated the entire exercise, manually removed the IBM foundational service, and it doesn't work. Additionally, I have reinstalled the CRC cluster and installed Maximo, commented out the line that fails during installation. The same error reappears.

![imagen](https://github.com/evilADevil/mas-local/assets/66454464/6e096a6b-d550-48f5-8f8f-73f79da2f02b)

**Comment by Pablofa8** [comment]
Certainly! Here's a revised and formal version of your message in English:

Hello,

I am experiencing the same issue. I believe this problem is related to my processor architecture (Apple Silicon M1).

Upon reviewing the YAML details of the pod, I found the following:
`affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
                - ppc64le
                - s390x
`
However, at the moment, I do not know how to resolve this issue. If anyone has any suggestions, I would appreciate your input.

**Comment by liyongc** [comment]
@Pablofa8 yes, the major problem here is crc node label is  **kubernetes.io/arch: arm64** which is not applicable for the common service  which is only for  **amd64**, I tried to use _kubectl label nodes crc kubernetes.io/arch=amd64 --overwrite_ to modify the crc node but it's revert back.
I submit a ticket to Redhat to see if there's solution for Apple M1 chip.

**Comment by evilADevil** [comment]
Maximo Application Suite does not support the ARM architecture at the moment, while OpenShift does. The labeling of the node is correct. @liyongc you may want to add a check to the script to inform the user and stop even before starting the install.
