### ISSUE TITLE
error build admin-build-config

### ISSUE THREAD

**Issue by GuilhermeFAC** [evilADevil/mas-local#11]
Hi @evilADevil , good afternoon

I'm doing a sno installation following the documentation, but my build pod gets two errors = "0/1 nodes are available: 1 not enough ephemeral storage. preemption: 0/1 nodes are available: 1 No preemption victims found for the pod input. "

![image](https://github.com/evilADevil/mas-local/assets/105025248/c5c95568-9b57-490f-b912-1788c88b0344)

what needs to be done?

**Comment by evilADevil** [comment]
Hi @GuilhermeFAC, usually this is not a persistent message. You can stop and restart the OCP Local, then restart the install that will pick up from where it left. Another thing you can try is to give more storage to OCP Local.

**Comment by GuilhermeFAC** [comment]
Hi @evilADevil, I needed to change the ephemeral memory on the ManageWorkspace instance to 50Gi admin and 30Gi all and the build succeeded
