### ISSUE TITLE
sno unstable

### ISSUE THREAD

**Issue by GuilhermeFAC** [evilADevil/mas-local#12]
Good morning @evilADevil and @liyongc 

I'm facing a problem, manage is installed successfully, but if I access the suite or manage I see that the vm's cpu consumption increases to the maximum and the sno drops and stays:
OpenShift: Unreachable (v4.12.13)
and I need to do a sno stop and crc start. it is unstable and it is not possible to make any changes to the manage settings, for example add addons, or add second language.

my crc configuration:

C:\Users\SRVITC>crc config view
- consent-telemetry : no
- CPU: 14
- disk-size: 200
-memory: 30720

machine
Intel(R) Core(TM) i7-14700K 3.40 GHz

128GB (usable: 128GB) DDR4 3200MHZ

1t nvme ssd

**Comment by evilADevil** [comment]
Your machine is bigger than the one I worked with. Your CPU should have 28 threads so you can try increase the config to 16 vCPU and 64 GB of RAM. Unfortunately there is not much we can do if OCP Local (not SNO) is unstable.

**Comment by GuilhermeFAC** [comment]
Ok, I understand, is it possible to install a sno on a local machine?
 do you have a document? a tutorial?

**Comment by evilADevil** [comment]
Installing a SNO is very possible on a local machine (bare metal) like it is possible to install it on a VM. I have a description on how to do that in IBM TechZone (https://github.com/evilADevil/mas-techzone/blob/main/MAS%20SNO%20on%20TechZone.pdf), and the steps are very similar for a bare metal machine. The only thing to pay a bit of attention is the network configuration, especially if the machine is on a local network.

**Comment by GuilhermeFAC** [comment]
Thanks @evilADevil , I changed cpus = 20 and 64Gi ram, now openshift local is normal.
