### ISSUE TITLE
Failed to apply default image tag "icrio/cpopen/ibm-maximo-operator-catalog:@@MAS_LATEST_CATALOG@@": couldn't parse image reference "icr.io/cpopen/ibm-maximo-operator-catalog:@@MAS_LATEST_CATALOG@@": invalid

### ISSUE THREAD

**Issue by DavidMecalco** [evilADevil/mas-local#13]
Hello, I have been testing the installation with MSSQL and encountered some errors during the script execution. The script runs, but I am having trouble deploying the `ibm-operator-catalog` operator. After checking the pod events, I found the following errors:

Failed to apply default image tag "icrio/cpopen/ibm-maximo-operator-catalog:@@MAS_LATEST_CATALOG@@": couldn't parse image reference "icr.io/cpopen/ibm-maximo-operator-catalog:@@MAS_LATEST_CATALOG@@": invalid

![Captura de pantalla 2024-08-07 201343](https://github.com/user-attachments/assets/b17a38ad-ab07-4cb7-bad2-261b9095a5e3)

I have configured the cluster correctly according to the documentation in the README file, but I am unable to move past this step.

![imagen](https://github.com/user-attachments/assets/8ef30881-f1cd-4540-862a-20b247935c65)

**Comment by evilADevil** [comment]
@DavidMecalco the masocpl.yml needs to be refreshed.
In particular:
- the mas_channel moved to 9.0.x
- the mas_app_channel moved to 9.0.x
- add mas_catalog_version: v9-240625-amd64 (or the latest catalog of interest) to resolve this reported error

**Comment by DavidMecalco** [comment]
Hi @evilADevil , I was able to update the values you mentioned in the masocpl.yml file. The installation continues without issues, but now I’m encountering an error with the namespace attribute. It shows the following error:

Install SLS Operator ---------------------------------------------------- 0.05s
ibm.mas_devops.sls : Check SLS version ---------------------------------- 0.05s
ibm.mas_devops.sls : Fail if mongocfg missing required mongo connection details --- 0.05s
ibm.mas_devops.ibm_catalogs : Determine whether this is an airgap environment --- 0.05s
ibm.mas_devops.sls : Read MongoDb config file --------------------------- 0.04s
ibm.mas_devops.sls : Fail if bootstrap.license_id is not set when bootstrap.license_file is set --- 0.04s
ibm.mas_devops.sls : Verify LicenseService CR --------------------------- 0.04s
ibm.mas_devops.ibm_catalogs : Load CASE bundle versions for the offline catalog --- 0.04s
ibm.mas_devops.mongodb : Retrieve image setting parts ------------------- 0.04s
ibm.mas_devops.sls : Load podTemplates configuration -------------------- 0.04s
command terminated with exit code 2
error: resource mapping not found for name: "masdemo-maslocal" namespace: "mas-masdemo-manage" from "mssql/manageworkspace-masdemo-maslocal.yaml": no matches for kind "ManageWorkspace" in version "apps.mas.ibm.com/v1"
ensure CRDs are installed first

![imagen](https://github.com/user-attachments/assets/37c6b8d0-b981-49fc-9658-97333739e256)

Thank you for your help. 
Regards

**Comment by evilADevil** [comment]
Sorry to be late in addressing this issue.The problem was due to the changes that were done in the MAS Ansible devops repository. I've updated this project and it should be working now with all the latest changes. Pls open a new issue in case you run into problems.
