### ISSUE TITLE
Help to fix Ansibles' 'improvement' 

### ISSUE THREAD

**Issue by CryCostaCry** [evilADevil/mas-local#14]
the prosses used to go much further, it use to run about 40 min. I used it about 3 weeks ago.
Now it is 100% kaput after only 1 min or so. Dies with obscure error

ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'

You bet it is a bug :)

I submitted error to Ansibles just get a 'spit in face' - it is evilADevil problem, go complain there.
Please help, at least let me know what version of Ansibles known to work OK with this script, so I pull that specific version

Below are log  chunks:

Cloning into '/opt/app-root/src/masloc/ansible-devops'...
error: uds.crt doesn't exist in local filesystem
ansible-galaxy [core 2.12.7]
  config file = /opt/app-root/src/ansible.cfg
  configured module search path = ['/opt/ansible/library']
  ansible python module location = /opt/app-root/lib64/python3.9/site-packages/ansible
  ansible collection location = /opt/app-root/lib64/python3.9/site-packages/ansible_collections
  executable location = /opt/app-root/bin/ansible-galaxy
  python version = 3.9.7 (default, Sep 13 2021, 08:18:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.2
  libyaml = True
Using /opt/app-root/src/ansible.cfg as config file
Starting galaxy collection install process

Calling Galaxy at https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/?limit=100&offset=100
[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/api/. Got an
unexpected error when getting available versions of collection
community.general: '/api/v3/plugin/ansible/content/published/collections/index/
community/general/versions/'
ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
the full traceback was:

Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'community.general'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/bin/ansible-galaxy", line 128, in <module>
    exit_code = cli.run()
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/cli/galaxy.py", line 569, in run
    return context.CLIARGS['func']()
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/cli/galaxy.py", line 86, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/cli/galaxy.py", line 1203, in execute_install
    self._execute_install_collection(
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/cli/galaxy.py", line 1230, in _execute_install_collection
    install_collections(
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/galaxy/collection/__init__.py", line 548, in install_collections
    dependency_map = _resolve_depenency_map(
  File "/opt/app-root/lib64/python3.9/site-packages/ansible/galaxy/collection/__init__.py", line 1364, in _resolve_depenency_map

**Comment by xocky2** [comment]
Hi @CryCostaCry 
Please try  adding the next line exactly after cloning the repository on masinst.bat
`oc exec %POD% -- bash -c "cd /opt/app-root/src/masloc/ansible-devops && git checkout a13461b159a94cb7e4a7cc15be583581cbf6dc38"`
![image](https://github.com/user-attachments/assets/eb412a6a-dbd8-470d-b55b-d1267f353712)

**Comment by CryCostaCry** [comment]
Thank you very much, it fixed the problem.

Just FYI, I hade to delete Catalog Source used by default by script and use new static catalog

**Comment by evilADevil** [comment]
@xocky2 and @CryCostaCry it has been a while I've not updated this project due to lack of time. I have created a new branch `mas9x_support` you may want to try. I have tested the "DB2 in the cluster" version, but was not able to fully test the external MSSQL one, because it looks like my OCP Local is not able to communicate with the host at the moment (investigating why).
If you'd like to test for me, download the new branch. I'd appreciate your help.

**Comment by CryCostaCry** [comment]
You are the man, I am thankful beyond any words. Trying it now, will take few hours

**Comment by evilADevil** [comment]
I've not heard on this anymore, therefore probably things got resolved. I've updated the whole project to use the latest MAS Ansible devops. Pls give it a try. I'll close this issue. Pls open a new one in case of need.
