### ISSUE TITLE
Custom Domain of local environment 

### ISSUE THREAD

**Issue by amitsindha** [evilADevil/mas-local#6]
Hi,

I have executed the script on my local machine and it’s working great.

question - is there any option where we can use the custom domain for Mas application in this setup?

There is one variable called “MAS_DOMAIN”  which is being used by the the Ansible script. 

Can we use this variable and make our own custom URL’s for Mas setup on local environment?

I am asking the question because we are looking for some local environment where we can connect from the  Mobile Emulator where public CA is required. In case if custom domain is available in the local OCP then we can setup public CA in one of front end web server like (NGINX, Apach)

Please let us know how the variable MAS_DOMAIN works in the Ansible script

From my side, I am planing to make one environment to setup and check. But if you already have idea of limitation then please let us know.

I will provide my input after my change and test result.

Thanks.

**Comment by evilADevil** [comment]
Unfortunately you cannot use that variable to set the domain. Check [https://github.com/ibm-mas/ansible-devops/tree/92fc64d12498ca243b06c28d15e4cd75c48dd86d/ibm/mas_devops/roles/suite_dns](https://github.com/ibm-mas/ansible-devops/tree/92fc64d12498ca243b06c28d15e4cd75c48dd86d/ibm/mas_devops/roles/suite_dns) and you will understand the purpose of that variable and its scope of support at the moment. In Windows, and I believe in MacOS, the domain is fixed for OpenShift Local and I don't think can be changed.
You mentioned in the other issue that you are running on a Mac, so @liyongc this is FYI.
