### ISSUE TITLE
installation hangs on mogodb cluster

### ISSUE THREAD

**Issue by witekwww** [evilADevil/mas-local#7]
Hi,
trying to use the script on both Linux and Windows OS, but in both cases installation does not go past 'create MongoDB cluster'.
I've managed to pinpoint the problem to the creating of PVC which throws error in log:
`mkdir: can't create directory '/data/pvc-954d7733-57a1-47b9-ba9e-dc337106b055': Permission denied`
Do You have any hints on that ?

**Comment by evilADevil** [comment]
Hi, where are you seeing that message? The PV directory is /mnt/pv-data, therefore I'm not sure where that /data directory comes from.

**Comment by amitsindha** [comment]
> Hi,
> trying to use the script on both Linux and Windows OS, but in both cases installation does not go past 'create MongoDB cluster'.
> I've managed to pinpoint the problem to the creating of PVC which throws error in log:
> `mkdir: can't create directory '/data/pvc-954d7733-57a1-47b9-ba9e-dc337106b055': Permission denied`
> Do You have any hints on that ?

Hi,

Are you trying to setup it on the physical machine or Virtual machine ?

**Comment by amitsindha** [comment]
> Hi,
> trying to use the script on both Linux and Windows OS, but in both cases installation does not go past 'create MongoDB cluster'.
> I've managed to pinpoint the problem to the creating of PVC which throws error in log:
> `mkdir: can't create directory '/data/pvc-954d7733-57a1-47b9-ba9e-dc337106b055': Permission denied`
> Do You have any hints on that ?

I tried this script last week and I got successes after some struggle and it took some more time around more than 24 hours.


After that, I investigated all and found that it was my mistakes while it took more time.

so I formatted my machine and started from the scratch with this script.


I would like to say I got success in around  14 hours (no dummy data)


I feel the script is working well because it’s just a wrapper of the original Ansible script.


I am glad i am able to achieve and got success to implement it on my local environment. Please share your experience and we We will try to figure out.

thanks & Regards,
Amit Sindha

**Comment by witekwww** [comment]
> Hi, where are you seeing that message? The PV directory is /mnt/pv-data, therefore I'm not sure where that /data directory comes from.

I was trying to fix this issue and I've changed the directory in ConfigMap.

Following Amit response I've deleted all of the CRC cluster and started over from scratch. The result is the same (apart from the directory):
`mkdir: can't create directory '/mnt/pv-data/pvc-0b656275-a4eb-468e-9019-34a619bdbbdd_mongoce_data-volume-mas-mongo-ce-0': Permission denied`
This error comes from the Pod helper-pod-create-pvc during the 
`TASK [ibm.mas_devops.mongodb : mongodb/community : Wait for stateful set to be ready] ***`

**Comment by evilADevil** [comment]
OK, now we are back to what I was expecting. If you want to change the directory, you need to make sure the right SELinux context is set in the host.
In any case, back to this issue, I guess you are using the latest released CRC ([2.11.0](https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/crc/2.11.0/). Red Hat has changed the SELinux context, this is why the local path provisioner fails. The good news is that, in this latest version, they delivers their own local provisioned storage class.
I will therefore use that and dismiss the creation of the modified Rancher one I was using.

**Comment by witekwww** [comment]
I'm on CRC 2.11.0 and You are correct: there is a default PV and StorageClass defined.
I will try setting this up with that default SC and let You know.

**Comment by evilADevil** [comment]
No need to. If you can wait a couple of hours, I'll upload the changes I'm just testing.

**Comment by witekwww** [comment]
Changing SC solved this problem. Thanks You!
Now facing another one on UDS install - I'm trying to install one locally instead of connecting to existing one, but that is not connected to this bug.

**Comment by evilADevil** [comment]
Be aware that UDS is quite big and won't fit in the specs described here for MAS Local.
