### ISSUE TITLE
Error from server (NotFound): error when creating "mssql/manageworkspace-masdemo-maslocal.yaml": namespaces "mas-masdemo-manage" not found  C:\MAS8\mas-local>

### ISSUE THREAD

**Issue by SrinivasGH** [evilADevil/mas-local#9]
I am trying to install MAS8.X on Windows 2019 Server using Sql server.
Stuck at below error.

Error from server (NotFound): error when creating "mssql/manageworkspace-masdemo-maslocal.yaml": namespaces "mas-masdemo-manage" not found
C:\MAS8\mas-local>

FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (1 retries left).
fatal: [localhost]: FAILED! => {"api_found": true, "attempts": 50, "changed": false, "resources": [{"apiVersion": "core.mas.ibm.com/v1", "kind": "Suite", "metadata": {"creationTimestamp": "2024-01-03T01:52:29Z", "finalizers": ["core.mas.ibm.com/finalizer"], "generation": 1, "labels":.......................................................
-...............................
, "message": "Failed to apply object: Namespace is required for cert-manager.io/v1.Issuer", "reason": "Failed", "status": "True", "type": "Failure"}]}}]}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=207  changed=14   unreachable=0    failed=1    skipped=73   rescued=0    ignored=0

Wednesday 03 January 2024  02:43:22 +0000 (0:50:48.056)       0:51:57.808 *****
===============================================================================
ibm.mas_devops.suite_verify : Wait for Suite Components to be ready (60s delay)  3048.06s
ibm.mas_devops.install_operator : Create subscription ------------------- 5.76s
ibm.mas_devops.suite_config : Apply configs ----------------------------- 4.67s
Gathering Facts --------------------------------------------------------- 2.42s
ibm.mas_devops.mongodb : community : install : Install the MongoDb Operator --- 1.85s
ibm.mas_devops.install_operator : Create ibm-entitlement secret --------- 1.59s
ibm.mas_devops.mongodb : Get cluster info ------------------------------- 1.48s
ibm.mas_devops.mongodb : community : check-mongo-exists : Check for existing mongo operator instance --- 1.23s
ibm.mas_devops.ibm_catalogs : detect-airgap : Look for the MAS ImageContentSourcePolicy --- 1.18s
ibm.mas_devops.mongodb : Create a issuer  in mongoce -------------------- 1.06s
ibm.mas_devops.mongodb : Create a Issuer for server certificate  in mongoce --- 0.92s
ibm.mas_devops.mongodb : community : check-mongo-exists : Check for existing mongodb instance --- 0.91s
ibm.mas_devops.suite_install : Create suite.ibm.com/v1 CR --------------- 0.77s
ibm.mas_devops.sls : Wait for License File & ID Upload (30s delay) ------ 0.77s
ibm.mas_devops.ibm_catalogs : Create IBM online catalog ----------------- 0.75s
ibm.mas_devops.mongodb : community : install : Configure anyuid permissions in the MongoDb namespace --- 0.71s
ibm.mas_devops.install_operator : Create operator group ----------------- 0.71s
ibm.mas_devops.mongodb : Lookup ibm-operator-catalog -------------------- 0.70s
ibm.mas_devops.common_services : Check if operator group is present in ibm-common-services already --- 0.69s
ibm.mas_devops.mongodb : community : install : Install MongoDBCommunity CRD --- 0.68s
ibm.mas_devops.sls : Wait for LicenseService to be running (30s delay) --- 0.67s
ibm.mas_devops.sls : Create the sls.ibm.com/v1.LicenseService ----------- 0.67s
ibm.mas_devops.mongodb : Create a ca certificate in mongoce ------------- 0.67s
ibm.mas_devops.sls : Create the Mongo Secret for SLS -------------------- 0.66s
ibm.mas_devops.cert_manager : Wait for ibm-cert-manager-operator to be ready (60s delay) --- 0.66s
ibm.mas_devops.mongodb : Create a server certificate in mongoce --------- 0.65s
ibm.mas_devops.sls : Lookup sls.ibm.com/v1.LicenseService --------------- 0.65s
ibm.mas_devops.mongodb : community : install : Create MongoDb cluster --- 0.64s
ibm.mas_devops.cert_manager : Install Foundation Services ibm-cert-manager operand request --- 0.63s
ibm.mas_devops.suite_install : Wait until the Suite CRD is available ---- 0.63s
ibm.mas_devops.common_services : Lookup ibm-common-service-operator packagemanifest --- 0.63s
ibm.mas_devops.mongodb : community : install : Lookup the ca.pem -------- 0.63s
ibm.mas_devops.sls : Wait for LicenseService to be ready (60s delay) ---- 0.63s
ibm.mas_devops.install_operator : Create operator group ----------------- 0.63s
ibm.mas_devops.mongodb : community : install : Create namespace & install RBAC --- 0.62s
ibm.mas_devops.sls : Lookup PackageManifest: ibm-sls -------------------- 0.62s
ibm.mas_devops.sls : Obtain License Service Certificate ----------------- 0.62s
ibm.mas_devops.suite_install : detect-airgap : Look for the MAS ImageContentSourcePolicy --- 0.62s
ibm.mas_devops.ibm_catalogs : Wait until CatalogSource/ibm-operator-catalog is Ready --- 0.62s
ibm.mas_devops.mongodb : community : install : Wait for stateful set to be ready --- 0.61s
ibm.mas_devops.install_operator : Create subscription ------------------- 0.61s
ibm.mas_devops.common_services : Create ibm-common-services namespace --- 0.61s
ibm.mas_devops.cert_manager : Increase common service cpu limit to account for increased cert privateKey sizings --- 0.61s
ibm.mas_devops.sls : Wait until the LicenseService CRD is available ----- 0.60s
ibm.mas_devops.install_operator : Create namespace ---------------------- 0.59s
ibm.mas_devops.mongodb : community : install : Wait for Mongo CR to report correct version --- 0.59s
ibm.mas_devops.sls : Wait for LicenseService to be initialized (30s delay) --- 0.58s
ibm.mas_devops.mongodb : community : install : Lookup admin password ---- 0.57s
ibm.mas_devops.mongodb : community : install : Check for existing metrics endpoint secret --- 0.57s
ibm.mas_devops.mongodb : community : install : Lookup mongo pods -------- 0.57s
ibm.mas_devops.common_services : Wait for Foundational Services resources to be ready (60s delay) --- 0.57s
ibm.mas_devops.mongodb : community : check-mongo-exists : Check for existing mongo operator instance --- 0.57s
ibm.mas_devops.sls : Create SLS Bootstrap secret ------------------------ 0.57s
ibm.mas_devops.cert_manager : Wait for cert-manager-webhook deployment to be ready (60s delay) --- 0.57s
ibm.mas_devops.mongodb : community : check-mongo-exists : Check for existing mongodb instance --- 0.57s
ibm.mas_devops.cert_manager : Check if Certificate Manager is already installed --- 0.57s
ibm.mas_devops.sls : Get cluster subdomain ------------------------------ 0.57s
ibm.mas_devops.mongodb : community : install : Check for existing service monitor --- 0.57s
ibm.mas_devops.mongodb : Lookup storage classes ------------------------- 0.57s
ibm.mas_devops.mongodb : Lookup ibm-operator-catalog -------------------- 0.56s
ibm.mas_devops.common_services : Install Foundational Services ---------- 0.56s
ibm.mas_devops.mongodb : community : install : Lookup the server.crt ---- 0.56s
ibm.mas_devops.sls : detect-airgap : Look for the MAS ImageContentSourcePolicy --- 0.55s
ibm.mas_devops.install_operator : Create namespace ---------------------- 0.55s
ibm.mas_devops.mongodb : community : install : Lookup the ca.crt -------- 0.55s
ibm.mas_devops.mongodb : community : install : Check for existing CA configmap --- 0.54s
ibm.mas_devops.mongodb : community : install : Create MAS MongoCfg ------ 0.54s
ibm.mas_devops.mongodb : community : install : Check for existing user password secret --- 0.53s
ibm.mas_devops.suite_install : Get cluster subdomain -------------------- 0.53s
ibm.mas_devops.mongodb : Lookup ibm-operator-catalog -------------------- 0.51s
ibm.mas_devops.gencfg_workspace : Copy Workspace to filesytem ----------- 0.41s
ibm.mas_devops.sls : Copy SLSCfg to filesytem --------------------------- 0.39s
ibm.mas_devops.mongodb : List yml files in common_vars/casebundles folder --- 0.33s
ibm.mas_devops.mongodb : Check if file exists in casebundles ------------ 0.32s
ibm.mas_devops.mongodb : community : install : Configure anyuid permissions for database service account --- 0.31s
ibm.mas_devops.suite_config : Find *.yml and *.yaml files in the MAS config directory --- 0.26s
ibm.mas_devops.mongodb : Check if file exists in casebundles ------------ 0.24s
ibm.mas_devops.mongodb : Check if file exists in casebundles ------------ 0.23s
ibm.mas_devops.mongodb : Check again if file exists in casebundles ------ 0.22s
ibm.mas_devops.mongodb : Check if file exists in casebundles ------------ 0.21s
ibm.mas_devops.mongodb : Check if file exists in casebundles ------------ 0.21s
ibm.mas_devops.sls : Override MongoDb facts bases on mongocfg ----------- 0.14s
ibm.mas_devops.mongodb : set_fact --------------------------------------- 0.13s
ibm.mas_devops.mongodb : include_tasks ---------------------------------- 0.13s
ibm.mas_devops.mongodb : set_fact --------------------------------------- 0.12s
ibm.mas_devops.suite_config : Debug the list of config files located ---- 0.09s
ibm.mas_devops.ibm_catalogs : Run the selected action ------------------- 0.08s
ibm.mas_devops.mongodb : Set existing_mongo_minor_version --------------- 0.08s
ibm.mas_devops.sls : Generate SLSCfg ------------------------------------ 0.07s
ibm.mas_devops.mongodb : community : install : Check for existing Grafana dashboard --- 0.07s
Install SLS Operator ---------------------------------------------------- 0.07s
ibm.mas_devops.mongodb : community : install : Call install-mongo to install/upgrade to mongo v5 or v6 --- 0.06s
ibm.mas_devops.sls : Run the specified action --------------------------- 0.06s
ibm.mas_devops.ansible_version_check : Verify minimum Ansible version is 2.10.3 --- 0.06s
ibm.mas_devops.mongodb : community : install : Create new MongoDb Grafana dashboard --- 0.06s
ibm.mas_devops.ibm_catalogs : Determine whether this is an airgap environment --- 0.06s
ibm.mas_devops.mongodb : Retrieve image setting parts ------------------- 0.05s
ibm.mas_devops.install_operator : Debug Entitlement Secret Creation ----- 0.05s
ibm.mas_devops.mongodb : debug ------------------------------------------ 0.05s
ibm.mas_devops.mongodb : set_fact --------------------------------------- 0.05s
command terminated with exit code 2
Error from server (NotFound): error when creating "mssql/manageworkspace-masdemo-maslocal.yaml": namespaces "mas-masdemo-manage" not found

C:\MAS8\mas-local>

**Comment by evilADevil** [comment]
Can you check or share the Suite CR, so that we understand what is the problem? Thx

**Comment by SrinivasGH** [comment]
[customresourcedefinition-suites.core.mas.ibm.com.zip](https://github.com/evilADevil/mas-local/files/13982503/customresourcedefinition-suites.core.mas.ibm.com.zip)
Sorry Alex, 
please find below and attached file
latest error in the suite custom resource is:


message: 'Failed to apply object: Namespace is required for [cert-manager.io/v1.Issuer](https://cert-manager.io/v1.Issuer)'

clients/crc/2.31.0/crc-windows-installer.zip
CRC version: 2.19.0+a71226
OpenShift version: 4.12.13
Podman version: 4.4.4

Detail error:
TASK [ibm.mas_devops.suite_verify : Configure namespace] ***********************
Friday 12 January 2024  17:58:00 +0000 (0:00:00.031)       0:14:27.430 ********
ok: [localhost] => {"ansible_facts": {"mas_namespace": "mas-masdemo-core"}, "changed": false}

TASK [ibm.mas_devops.suite_verify : Wait for Suite Components to be ready (60s delay)] ***
Friday 12 January 2024  17:58:00 +0000 (0:00:00.028)       0:14:27.459 ********
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (50 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (49 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (48 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (47 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (46 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (45 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (44 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (43 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (42 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (41 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (40 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (39 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (38 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (37 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (36 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (35 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (34 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (33 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (32 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (31 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (30 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (29 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (28 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (27 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (26 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (25 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (24 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (23 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (22 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (21 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (20 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (19 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (18 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (17 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (16 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (15 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (14 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (13 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (12 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (11 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (10 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (9 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (8 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (7 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (6 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (5 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (4 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (3 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (2 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (1 retries left).
fatal: [localhost]: FAILED! => {"api_found": true, "attempts": 50, "changed": false, "resources": [{"apiVersion": "core.mas.ibm.com/v1", "kind": "Suite", "metadata": {"creationTimestamp": "2024-01-10T01:31:44Z", "finalizers": ["core.mas.ibm.com/finalizer"], "generation": 1, "labels": {"mas.ibm.com/instanceId": "masdemo"}, "managedFields": [{"apiVersion": "core.mas.ibm.com/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:metadata": {"f:labels": {".": {}, "f:mas.ibm.com/instanceId": {}}}, "f:spec": {".": {}, "f:certManagerNamespace": {}, "f:domain": {}, "f:license": {".": {}, "f:accept": {}}, "f:settings": {".": {}, "f:dataDictionary": {".": {}, "f:catalog": {}}, "f:icr": {".": {}, "f:cp": {}, "f:cpopen": {}}, "f:manualCertMgmt": {}}}}, "manager": "OpenAPI-Generator", "operation": "Update", "time": "2024-01-10T01:31:44Z"}, {"apiVersion": "core.mas.ibm.com/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:metadata": {"f:finalizers": {".": {}, "v:\"core.mas.ibm.com/finalizer\"": {}}}}, "manager": "ansible-operator", "operation": "Update", "time": "2024-01-10T01:32:24Z"}, {"apiVersion": "core.mas.ibm.com/v1", "fieldsType": "FieldsV1", "fieldsV1": {"f:status": {".": {}, "f:conditions": {}}}, "manager": "ansible-operator", "operation": "Update", "subresource": "status", "time": "2024-01-12T18:33:42Z"}], "name": "masdemo", "namespace": "mas-masdemo-core", "resourceVersion": "199390", "uid": "ABC......"}, "spec": {"certManagerNamespace": "", "domain": "masdemo.apps-crc.testing", "license": {"accept": true}, "settings": {"dataDictionary": {"catalog": "ibm-operator-catalog"}, "icr": {"cp": "cp.icr.io/cp", "cpopen": "icr.io/cpopen"}, "manualCertMgmt": false}}, "status": {"conditions": [{"lastTransitionTime": "2024-01-10T01:32:33Z", "message": "No components are currently installed", "reason": "InstallPending", "status": "False", "type": "Ready"}, {"lastTransitionTime": "2024-01-10T01:32:33Z", "message": "", "reason": "", "status": "False", "type": "Successful"}, {"lastTransitionTime": "2024-01-12T18:33:38Z", "message": "Running reconciliation", "reason": "Running", "status": "False", "type": "Running"}, {"ansibleResult": {"changed": 0, "completion": "2024-01-12T18:33:42.458011", "failures": 1, "ok": 16, "skipped": 9}, "lastTransitionTime": "2024-01-12T18:33:42Z", "message": "Failed to apply object: Namespace is required for cert-manager.io/v1.Issuer", "reason": "Failed", "status": "True", "type": "Failure"}]}}]}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=297  changed=19   unreachable=0    failed=1    skipped=88   rescued=0    ignored=0

**Comment by SrinivasGH** [comment]
i am using the package from here and updated as recommended.
https://github.com/evilADevil/mas-local
Server specs are also same as recommended. Any help is appreciated. 
https://github.com/evilADevil

**Comment by SrinivasGH** [comment]
> Can you check or share the Suite CR, so that we understand what is the problem? Thx

i am using the package from here and updated as recommended.
https://github.com/evilADevil/mas-local
Server specs are also same as recommended. Any help is appreciated.

**Comment by SrinivasGH** [comment]
[Suite-masdemo.yaml.txt](https://github.com/evilADevil/mas-local/files/13983008/Suite-masdemo.yaml.txt)
> Can you check or share the Suite CR, so that we understand what is the problem? Thx

[customresourcedefinition-suites.core.mas.ibm.com.zip](https://github.com/evilADevil/mas-local/files/13982507/customresourcedefinition-suites.core.mas.ibm.com.zip)

**Comment by SrinivasGH** [comment]
@evilADevil Sorry for late response. For some reason i missed alert and i tried to respond back on your query. Please advice.

**Comment by evilADevil** [comment]
@SrinivasGH it looks like the ansible devops collection had a bug that was fixed last week. Therefore I suggest you to clean up the environment and retry, given the scripts here download always the latest version.

**Comment by SrinivasGH** [comment]
> @SrinivasGH it looks like the ansible devops collection had a bug that was fixed last week. Therefore I suggest you to clean up the environment and retry, given the scripts here download always the latest version.

Will do. Thank you.

**Comment by SrinivasGH** [comment]
> > @SrinivasGH it looks like the ansible devops collection had a bug that was fixed last week. Therefore I suggest you to clean up the environment and retry, given the scripts here download always the latest version.
> 
> Will do. Thank you.

Is that CRC latest you mean? https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/
https://github.com/evilADevil/mas-local - it says 2 months last update. Please confirm.

**Comment by SrinivasGH** [comment]
@evilADevil , Good Evening.
Thank you So much, I did get super user credentials but  stuck on workspace and CRC error:

1. TASK [ibm.mas_devops.suite_app_verify : Wait for application workspace to be ready (480s delay)] ***
Saturday 20 January 2024  03:13:40 +0000 (0:00:00.039)       0:23:55.448 ******
FAILED - RETRYING: [localhost]: Wait for application workspace to be ready (480s delay) (60 retries left).
As per the server configurations:
I have 16 Core CPU, 64GB RAM and 350GB of Hard Disk, i don't see issue with Infra, 

2. CRC is not stable keep getting : {"error":"server_error","error_description":"The authorization server encountered an unexpected condition that prevented it from fulfilling the request.","state":"5a5b021f"}

requesting your help.

**Comment by evilADevil** [comment]
If you have MAS Core running, can you check what the Manage application status is and report here?

**Comment by SrinivasGH** [comment]
@evilADevil, Good Morning Manage Application still not in the Suite Navigator list.
From configurations i see below error, not sure if this is stopping from creating Workspace.
Error
JDBC configuration was unable to be verified: [IBM][CLI Driver][DB2/LINUXX8664] SQL0601N The name of the object to be created is identical to the existing name "MAXIMO.MYTESTTABLE" of type "TABLE". SQLSTATE=42710 SQLCODE=-601

**Comment by evilADevil** [comment]
I'm not sure I understand what you mean by "Manage Application still not in the Suite Navigator list" You should see Manage in the MAS admin console in a activating state. If you don't see that, it means you don't have a running MAS Core. Have you tried to log on MAS admin? Have you provided a valid license file? I have the impression you have not, therefore MAS Core is installed, but won't deploy and activate any applications.

**Comment by SrinivasGH** [comment]
@evilADevil 
I got credentials and i am able to login to below URL's.
https://api.masdemo.apps-crc.testing/
https://admin.masdemo.apps-crc.testing/
please see below SS
![image](https://github.com/evilADevil/mas-local/assets/38468490/3da01cd2-3e9e-4c7f-8b61-96ebe571d2e1)

![image](https://github.com/evilADevil/mas-local/assets/38468490/e4f253f2-e00d-44ab-831c-c846167ac20f)

**Comment by evilADevil** [comment]
Good you have a running MAS Base. It looks like Manage is not able to build their images. You may need to go to its namespace and check the build logs on why that is the case.

**Comment by SrinivasGH** [comment]
@evilADevil , on Maximo screen on right top corner:
AIUCO1999E: Internal Server Error: HTTPSConnectionPool(host='10.217.4.1', port=443): Max retries exceeded with url: /apis/packages.operators.coreos.com/v1/namespaces/openshift-marketplace/packagemanifests/ibm-mas-manage (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4b7fcc9ee0>: Failed to establish a new connection: [Errno 111] ECONNREFUSED'))

Like I mentioned when i verified the DB connection verification also failing
![image](https://github.com/evilADevil/mas-local/assets/38468490/82420f0c-de0e-4360-aacc-e0a752dd75e3)

And Openshift not stable:
![image](https://github.com/evilADevil/mas-local/assets/38468490/7f9bc1d7-69b9-4d29-946d-bad2339b28b8)

**Comment by evilADevil** [comment]
From the error, you have a dirty DB with a table the installation is trying to create and instead is already there. May be this is due to a previous attempt to install Manage. You need to have a clean environment.

**Comment by SrinivasGH** [comment]
@evilADevil , Thank you! let me me try again with start over. :). Just as a advise, when you have perpetual license from IBM what is the best approach to have MAS stable Env, single node is good enough for internal integration R&D and Development. 
Like to have Windows machine  or Linux machine and install openshift and then MAS on it. I am not expecting to loose my data once installed and configured. it should retain forever.

**Comment by evilADevil** [comment]
I do not suggest to install OCP Local if you want to have a stable environment. Those OCP environments cannot be updated. You should target a SNO.

**Comment by SrinivasGH** [comment]
@evilADevil SNO can i do on Windows machine or should i get RHL VM with open shift? sorry for bombarding with questions.

**Comment by SrinivasGH** [comment]
@evilADevil , i tried new install with sql db, any help please
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (44 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (43 retries left).
error: unable to recognize "mssql/manageworkspace-masdemo-maslocal.yaml": Get "https://api.crc.testing:6443/api?timeout=32s": read tcp 127.0.0.1:62225->127.0.0.1:6443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by evilADevil** [comment]
go ahead and restart the install. it will skip all the steps already done and continue where it left.

**Comment by evilADevil** [comment]
> @evilADevil SNO can i do on Windows machine or should i get RHL VM with open shift? sorry for bombarding with questions.

SNO runs on a bare metal machine and has its own OS which is CoreOS. OpenShift local can run hosted on Windows, MacOS or Linux. SNO and OpenShift Local are two different things, so don't confuse the two.

**Comment by SrinivasGH** [comment]
> > @evilADevil SNO can i do on Windows machine or should i get RHL VM with open shift? sorry for bombarding with questions.
> 
> SNO runs on a bare metal machine and has its own OS which is CoreOS. OpenShift local can run hosted on Windows, MacOS or Linux. SNO and OpenShift Local are two different things, so don't confuse the two.

Thank you Sir for clarification!

**Comment by SrinivasGH** [comment]
@evilADevil 
tried twice sir, with masinst mssql from C:\MAS8\mas-local, no luck
crc status:
CRC VM:          Running
OpenShift:       Running (v4.12.13)
RAM Usage:       19.24GB of 37.91GB
Disk Usage:      46.19GB of 214.2GB (Inside the CRC VM)
Cache Usage:     44.94GB

Tried 50 times:
}

TASK [ibm.mas_devops.suite_verify : Configure namespace] ***********************
Wednesday 24 January 2024  14:39:20 +0000 (0:00:00.046)       0:01:02.336 *****
ok: [localhost] => {"ansible_facts": {"mas_namespace": "mas-masdemo-core"}, "changed": false}

TASK [ibm.mas_devops.suite_verify : Wait for Suite Components to be ready (60s delay)] ***
Wednesday 24 January 2024  14:39:20 +0000 (0:00:00.046)       0:01:02.383 *****
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (50 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (49 retries left).
FAILED - RETRYING: [localhost]: Wait for Suite Components to be ready (60s delay) (48 retries left).
.............................. Finally errored out

ibm.mas_devops.mongodb : debug ------------------------------------------ 0.05s
command terminated with exit code 2
error: resource mapping not found for name: "masdemo-maslocal" namespace: "mas-masdemo-manage" from "mssql/manageworkspace-masdemo-maslocal.yaml": no matches for kind "ManageWorkspace" in version "apps.mas.ibm.com/v1"
ensure CRDs are installed first

**Comment by SrinivasGH** [comment]
@evilADevil ,
do you think last line of masinst.bat causing this issue? does it need any update sir.
REM Run the playbook
oc exec %POD% -- bash -c "cd masloc/ansible-devops/ibm/mas_devops && export MAS_APP_SETTINGS_DEMODATA=True && ansible-playbook ibm.mas_devops.masocpl"
if "%1" EQU "mssql" (oc apply -f mssql/manageworkspace-masdemo-maslocal.yaml)

one more clarification: As i see OC is not stable without even mas sometime on CRC 2.19 . Can i use latest version of CRC for this MAS install or i have to be on on CRC 2.19?

**Comment by evilADevil** [comment]
From the last error you reported, it seems that Manage is not in the cluster, therefore the line you think causing the error, instead is just suffering the fact that the cluster is not configured correctly.
On the CRC question, you need to be on a version that includes OCP v4.12 which is the current supported version. You can try using OCP 4.14 that will be supported shortly...

**Comment by SrinivasGH** [comment]
> From the last error you reported, it seems that Manage is not in the cluster, therefore the line you think causing the error, instead is just suffering the fact that the cluster is not configured correctly. On the CRC question, you need to be on a version that includes OCP v4.12 which is the current supported version. You can try using OCP 4.14 that will be supported shortly...

Thank you!

**Comment by khalilguelmami** [comment]
@evilADevil , Hello, can you please advise? I don't see what I messed up that caused the cluster to not be configured correctly.

**Comment by evilADevil** [comment]
Sorry to be late in addressing this issue.The problem was probably due to the changes that were done in the MAS Ansible devops repository. I've updated this project and it should be working now with all the latest changes. Pls open a new issue in case you run into problems.
